version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: taste-backend-db
    ports:
      - 5432:5432
    networks:
      - web_nw
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    
  app:
    build:
      context: .
      network: host
    container_name: taste-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5000:5000
    networks:
      - web_nw
    volumes:
      - .:/usr/src/app

volumes:
  pgdata:

networks:
  web_nw:
    name: taste-backend
    driver: bridge
